# Generated by Django 4.2.11 on 2026-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for the project page.', null=True, upload_to='projects/banners/'),
        ),
    ]
