# Generated by Django 4.2.11 on 2026-05-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_featuredproject_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='app_link',
            field=models.URLField(blank=True, help_text='Link to the mobile app (App Store/Play Store).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='website_link',
            field=models.URLField(blank=True, help_text='Link to the live website.', max_length=500, null=True),
        ),
    ]
