# Generated by Django 4.2.11 on 2026-05-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_featuredproject_app_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproject',
            name='app_link',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='website_link',
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='raised',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Link label, e.g. 'Website', 'App Store'.", max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.featuredproject')),
            ],
            options={
                'verbose_name': 'Project Link',
                'verbose_name_plural': 'Project Links',
                'ordering': ['order'],
            },
        ),
    ]
