# Generated by Django 4.2.11 on 2026-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_featuredproject_app_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='featuredproject',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='Primary category tag (legacy). Use Categories field for multiple categories.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.projectcategory'),
        ),
    ]
