# Generated by Django 4.2.11 on 2026-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectcategory_alter_featuredproject_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='categories',
        ),
        migrations.AlterField(
            model_name='featuredproject',
            name='tag',
            field=models.CharField(blank=True, help_text='Primary category tag (legacy).', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Multiple tags for categorization.', related_name='projects', to='projects.tag'),
        ),
    ]
