# Generated by Django 4.2.11 on 2026-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_tag_remove_featuredproject_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproject',
            name='tag',
        ),
        migrations.AlterField(
            model_name='featuredproject',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select one or more tags for this project.', related_name='projects', to='projects.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
