# Generated by Django 4.2.11 on 2026-05-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projecttag_remove_featuredproject_tags_delete_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproject',
            name='raised',
        ),
    ]
