# Generated by Django 4.2.11 on 2026-05-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_featuredproject_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredproject',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='project_video',
        ),
        migrations.RemoveField(
            model_name='featuredproject',
            name='project_video_url',
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='banner',
            field=models.FileField(blank=True, help_text='Upload a banner image or video.', null=True, upload_to='projects/banners/'),
        ),
    ]
