# Generated by Django 4.2.11 on 2026-05-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_featuredproject_banner_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproject',
            old_name='banner',
            new_name='project_image_item',
        ),
    ]
