# Generated by Django 4.2.11 on 2026-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_banner_featuredproject_project_image_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproject',
            name='banner_video',
            field=models.FileField(blank=True, help_text='Banner video for the project.', null=True, upload_to='projects/videos/'),
        ),
        migrations.AlterField(
            model_name='featuredproject',
            name='project_image_item',
            field=models.ImageField(blank=True, help_text='Banner image for the project.', null=True, upload_to='projects/banners/'),
        ),
    ]
