# Generated by Django 4.2.11 on 2026-04-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR (or your preferred currency).', max_digits=10)),
                ('price_label', models.CharField(blank=True, default='', help_text="Optional label, e.g. '/month', 'one-time', 'starting from'.", max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text="Highlight this package (e.g. 'Most Popular').")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing Package',
                'verbose_name_plural': 'Pricing Packages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=300)),
                ('is_included', models.BooleanField(default=True, help_text='False = feature is NOT included (shown as crossed out).')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pricing.pricingpackage')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['order'],
            },
        ),
    ]
