# Generated by Django 4.2.11 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Direct URL to the video (e.g. S3 link, YouTube embed, or CDN URL).', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Only one video should be active. Saving a new active video will deactivate others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Video',
                'verbose_name_plural': 'Home Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
