# Generated by Django 4.2.11 on 2026-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homevideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file from your computer.', null=True, upload_to='hero_videos/'),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Alternatively, provide a direct URL to a video (e.g. S3 link). Used if no file is uploaded.', max_length=500),
        ),
    ]
