# Generated by Django 4.2.11 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, help_text='Client profile photo (optional).', null=True, upload_to='feedback/avatars/')),
                ('client_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Client testimonial / feedback text.')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating out of 5.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedbacks',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
