# Generated by Django 4.2.11 on 2026-05-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='client_image',
            new_name='image',
        ),
    ]
