# Generated by Django 4.2.11 on 2026-05-01 18:24

import apps.feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_client_image_clientfeedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='description',
            field=models.TextField(help_text='Client testimonial / feedback text. Max 25 words.', validators=[apps.feedback.models.validate_word_count]),
        ),
    ]
