# Generated by Django 4.2.11 on 2026-05-01 18:26

import apps.feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_clientfeedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='description',
            field=models.TextField(help_text='Client testimonial / feedback text. Max 25 words and 200 characters.', max_length=200, validators=[apps.feedback.models.validate_word_count]),
        ),
    ]
