# Generated by Django 4.2.11 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('pricing', 'Pricing'), ('feedback', 'Feedback / Testimonials'), ('contact', 'Contact')], db_index=True, help_text='Unique identifier for the page. Used by the frontend to fetch SEO data.', max_length=50, unique=True)),
                ('meta_title', models.CharField(help_text='Page title shown in browser tab and Google results (max 70 chars).', max_length=70)),
                ('meta_description', models.CharField(help_text='Short description shown in Google snippets (max 160 chars).', max_length=160)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords.\nSuggested: software development in Trivandrum, affordable software company Kerala, best web development company Kochi, web development Calicut, web development Idukki, web development Wayanad')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing (Facebook, LinkedIn).', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description for social sharing.', max_length=300)),
                ('og_image', models.ImageField(blank=True, help_text='Open Graph image (1200×630px recommended).', null=True, upload_to='seo/og/')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from the default.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'ordering': ['page'],
            },
        ),
    ]
