# Generated by Django 4.2.11 on 2026-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlogo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientlogo',
            name='website_url',
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='alt_text',
            field=models.CharField(default='', help_text='Alternative text for the logo.', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='logo',
            field=models.ImageField(help_text='Client logo / icon.', upload_to='clients/logos/'),
        ),
    ]
